# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='kcal_total',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='last_modified',
        ),
    ]
