# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0002_auto_20181118_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='content',
        ),
    ]
