# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_remove_ingredient_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='article_number',
            field=models.TextField(max_length=20),
        ),
    ]
