# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_auto_20181118_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='article_number',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
