# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredient', '0005_auto_20181118_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.IntegerField()),
                ('title', models.CharField(max_length=140)),
                ('ingredient_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complexity', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('total_kcal', models.IntegerField()),
                ('unit_of_measure_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'recipes',
                'verbose_name': 'recipe',
            },
        ),
    ]
