# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False,  verbose_name='ID', auto_created=True),
        ),
    ]
