# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0007_auto_20181120_0046'),
        ('recipe', '0004_auto_20181121_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ingredient.Ingredient'),
            preserve_default=False,
        ),
    ]
