# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='unit_of_measure_amt',
        ),
    ]
