# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20181124_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-last_modified'], 'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='complexity',
        ),
    ]
