# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20181124_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
