export const ADD_ERROR = "ADD_ERROR"
export const REMOVE_ERROR = "REMOVE_ERROR"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const LOAD_INGREDIENTS = "LOAD_INGREDIENTS"
export const UPDATE_INGREDIENT_QUERY = "UPDATE_INGREDIENT_QUERY"
export const UPDATE_RECIPE_QUERY = "UPDATE_RECIPE_QUERY"
export const LOAD_RECIPES = "LOAD_RECIPES"

