# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexity', models.CharField(choices=[('1', 'Very Low'), ('2', 'Low'), ('3', 'Normal'), ('4', 'high'), ('5', 'Very High')], default='3', max_length=1)),
                ('title', models.CharField(max_length=255)),
                ('time_taken', models.TimeField()),
                ('instructions', models.TextField()),
                ('total_kcal', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost_crcy', models.CharField(max_length=3)),
                ('image', models.TextField(max_length=65536)),
                ('image_url', models.URLField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
